pipeline {
  agent any
  stages{
    stage("Git_Checkout"){
      steps{
      git branch : 'main', url :'https://github.com/vishnugonela/pythonapp.git'
    }
}
    stage("Building_Image"){
      steps{
        sh '''
        cd ${WORKSPACE}/

        docker image build -t pythonapp .
        '''
  }
}
    stage("Tagging_pushing"){
      steps{
        withCredentials([string(credentialsId: 'docker_pass', variable: 'Docker_TOKEN')]){
        
          sh '''
          docker image tag pythonapp:latest sravani3985/pythonapp:latest
          docker login -u sravani3985 -p ${Docker_TOKEN}
          docker image push sravani3985/pythonapp:latest
          '''
        }
    
      }
    }
    stage("deployment_on_slave"){
      agent {
        label 'Node1'
      }
      steps{
        sh '''
        if docker container ls -a | grep c1
        then
        docker container rm -f c1
        docker container run -d --name c1 -p 8081:80 sravani3985/pythonapp:latest
        else
        docker container run -d --name c1 -p 8081:80 sravani3985/pythonapp:latest
        fi
        '''
  }
}
    stage("validate_application"){
      agent{
        label 'Node1'
      }
    steps{
      sh '''
      docker container ls -a | grep c1
      docker logs c1
      '''
  }
}
}
}

