FROM ubuntu:24.04

RUN apt update && apt install -y openssh-server

RUN mkdir /var/run/sshd

RUN echo "root:123" | chpasswd

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

ENTRYPOINT ["/usr/sbin/sshd", "-D"]
