pipeline {
    agent any 

    stages {
        stage('Build') {
            steps {
                echo 'Building the application...' 
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                echo " Executing code from Linux repo"
                bash ${WORKSPACE}/linux/script.sh
                echo 'Deploying the application...'
            }
        }
    }
}
