pipeline {
    agent any 

    stages {
        stage('Build') {
            steps {
                sh '''
                for i in {1..5}
                do
                echo 'Building the application...'
                sleep 5
                done
                '''
                
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }
        stage('Deploy') {
            steps {
                echo " Executing code from Linux repo"
                sh "bash ${WORKSPACE}/linux/script.sh"
                echo 'Deploying the application...'
            }
        }
    }
}
