
name: Sample_workflow_ci-cd
on:
  push:
    branches: [ "vishnu" ]
  pull_request:
    branches: [ "vishnu" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: deployment step
          run: |
             echo "Hostname is $hostname"
             echo "IP of the host is $(hostname -I)"
